name: 'Deploy'

on:
  push:
    branches: [ production ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Do a git checkout including submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LWTV_STATUS_SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.LWTV_STATUS_HOST }}
          REMOTE_USER: ${{ secrets.LWTV_STATUS_USER }}
          TARGET: ${{ secrets.LWTV_STATUS_TARGET }}
          EXCLUDE: "/.git/, /.github/"
